### ISSUE TITLE
Mysql 7 修改了 NO_ENGINE_SUBSTITUTION 启动报告 redis错误

### ISSUE THREAD

**Issue by biitt06** [welliamcao/OpsManage#100]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 176, in run
    worker.run()
  File "/usr/local/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/local/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/local/lib/python2.7/site-packages/asgi_redis/core.py", line 168, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
==========================
# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
#
requirepass

# Command renaming.
#
==============
djcelery.setup_loader()
BROKER_URL = 'redis://10.247.60.30:6379/3'
CELERY_RESULT_BACKEND = 'djcelery.backends.database.DatabaseBackend'

**Comment by welliamcao** [comment]
redis-cli -h localhost -p 6379 info 执行看一下结果
