### ISSUE TITLE
V3测试版本BUG反馈

### ISSUE THREAD

**Issue by welliamcao** [welliamcao/OpsManage#154]
建议按照下面格式反馈
![image](https://user-images.githubusercontent.com/5885314/52842853-52977580-313b-11e9-8108-76f6f018be4e.png)

**Comment by Yansre** [comment]
【用户管理新增用户页面不显示】在用户管理栏新增用户，数据库已写入，但是页面不展示

**Comment by welliamcao** [comment]
什么浏览器？

**Comment by blueiq** [comment]
【批量导入和下载点击无反应】资产列表中批量导入和下载点击无反应。
【部署工具日志】部署工具缺日志记录页面。
【工单申请缺失发布模块】工单申请缺乏发布申请。

**Comment by Yansre** [comment]
【部署工具-脚步工具js无法加载】cdn.bootcss.comjs无法加载，建议放在本地

**Comment by jinrong58** [comment]
【用户管理新增用户页面不显示】在用户管理栏新增用户，数据库已写入，但是页面不展示(谷歌浏览器）
此时，【添加项目】“负责人”处为空，写入项目名，点击“保存”，提示添加成功，这时“基础资产”页点进去看不到“添加”按钮，左侧的导航树完全死掉，哪个菜单也点击不了了。

**Comment by welliamcao** [comment]
@Yansre @jinrong58 用户中心看不到用户的原因是因为如果用MySQL5.7，django-rest-framework的DateField不能正常工作，5.7以下的版本就没问题，现在已经改成DateTimeField兼容5.6、5.7。
@blueiq 批量导入/部署工具日志的功能还没写，批量导出用户中心可以导出，代码发布不打算走工单，因为可以为每个项目成员配置权限，也有相关的部署记录。

**Comment by jinrong58** [comment]
我用的就是5.6的mysql（mysql  Ver 14.14 Distrib 5.6.43-84.3）。不过用了你新更的代码后，我上边提到的问题解决了。

**Comment by jinrong58** [comment]
【左侧导航菜单最下边的4个按钮无效】“setting”、“fullscreen”、“lock”、“logout”都不能用。谷歌和火狐浏览器都试了，表现一致。

**Comment by Yansre** [comment]
【资产批量操作bug】
1.点击第二页或第三页，全选会跳回第一页，但这时再点第二页依旧是全选状态继续操作第三页则无法选中，重复跳会第一页
2.资产全部展开100个，选择更新资产信息，提示资产修改失败，

**Comment by welliamcao** [comment]
@jinrong58 

> 【左侧导航菜单最下边的4个按钮无效】“setting”、“fullscreen”、“lock”、“logout”都不能用。谷歌和火狐浏览器都试了，表现一致。

这个几个栏目确实没用%>_<%

**Comment by welliamcao** [comment]
> 【资产批量操作bug】
> 1.点击第二页或第三页，全选会跳回第一页，但这时再点第二页依旧是全选状态继续操作第三页则无法选中，重复跳会第一页
> 2.资产全部展开100个，选择更新资产信息，提示资产修改失败，

资产列表，还是用户中心的？

**Comment by Yansre** [comment]
> > 【资产批量操作bug】
> > 1.点击第二页或第三页，全选会跳回第一页，但这时再点第二页依旧是全选状态继续操作第三页则无法选中，重复跳会第一页
> > 2.资产全部展开100个，选择更新资产信息，提示资产修改失败，
> 
> 资产列表，还是用户中心的？

资产列表

**Comment by 18951656076** [comment]
【基础资产操作bug】
1.录入项目应用、机房信息等资料后，再次打开此页面看不见已添加的信息，但在数据库中能够查到添加的数据；
2.点击基础资产页面后，再点击其他功能页面无反应，只有点击左上角的主页按钮后才有反应；
3.另外，想问下，点击每个功能页面，真个网页页面都要刷新下，体验感较差，是否可以更改。

**Comment by welliamcao** [comment]
@18951656076 你是什么浏览器？

**Comment by 18951656076** [comment]
> @18951656076 你是什么浏览器？

chrome 65.0.3325.181

**Comment by welliamcao** [comment]
> > @18951656076 你是什么浏览器？
> 
> chrome 65.0.3325.181

什么时候的代码？

**Comment by 18951656076** [comment]
> > > @18951656076 你是什么浏览器？
> > 
> > 
> > chrome 65.0.3325.181
> 
> 什么时候的代码？

昨天晚上download的

**Comment by welliamcao** [comment]
> > > > @18951656076 你是什么浏览器？
> > > 
> > > 
> > > chrome 65.0.3325.181
> > 
> > 
> > 什么时候的代码？
> 
> 昨天晚上download的

升级浏览器或者火狐浏览器会遇到这个问题？或者用开发者模式看一下接口是不是返回了数据。

**Comment by blueiq** [comment]
[sudo无效]模块工具等ansible使用普通用户sudo无效，提示权限不足，该用户配置过可以sudo，使用v2版本是可以的。

**Comment by 18951656076** [comment]
> > > > > @18951656076 你是什么浏览器？
> > > > 
> > > > 
> > > > chrome 65.0.3325.181
> > > 
> > > 
> > > 什么时候的代码？
> > 
> > 
> > 昨天晚上download的
> 
> 升级浏览器或者火狐浏览器会遇到这个问题？或者用开发者模式看一下接口是不是返回了数据。

知道了原因 我的mysql用的5.7 sql_mode 对group有限制。

**Comment by 18951656076** [comment]
【资产列表bug】删除设备时显示删除失败 ，不能删除设备。最新的v3代码。

**Comment by welliamcao** [comment]
@18951656076 最新提交已经修复。

**Comment by frank0826** [comment]
![image](https://user-images.githubusercontent.com/11606105/55291194-7292a800-540e-11e9-9c5b-0678fbcd21e3.png)
代码部署路径，JS 未获取到 opsmanage.in配置path

**Comment by blueiq** [comment]
[sudo无效]模块工具等ansible使用普通用户sudo无效，提示权限不足，该用户配置过可以sudo，使用v2版本是可以的。看默认become都是True的
![image](https://user-images.githubusercontent.com/35997550/55776022-e9463a00-5acd-11e9-8885-3be39f2fd032.png)

**Comment by peterwoo1224** [comment]
貌似在剧本工具创建部署剧本后，无法删除，点击删除后还是存在。V3刚下载的代码

**Comment by sunsunzhe** [comment]
使用模块工具，没有反应
![图片](https://user-images.githubusercontent.com/41135795/56714282-e94d6780-6766-11e9-8617-eec4ad92c071.png)

**Comment by welliamcao** [comment]
> 使用模块工具，没有反应
> ![图片](https://user-images.githubusercontent.com/41135795/56714282-e94d6780-6766-11e9-8617-eec4ad92c071.png)

是不是配置了uwsgi

**Comment by welliamcao** [comment]
@sunsunzhe 是不是配置了uwsgi？

**Comment by welliamcao** [comment]
@peterwoo1224 已修复

**Comment by sunsunzhe** [comment]
> 
> 
@welliamcao 没有，按照安装文档配置的

**Comment by peterwoo1224** [comment]
> > 
> 
> @welliamcao没有，按照安装文档配置的

![image](https://user-images.githubusercontent.com/24648358/56857503-ff466c80-69a0-11e9-9bd7-4776f9170d9e.png)
点击删除页面还是存在，右上角一闪而过这个窗口，显示Success，但是内容是失败

**Comment by peterwoo1224** [comment]
> @peterwoo1224 已修复

![image](https://user-images.githubusercontent.com/24648358/56857532-3f0d5400-69a1-11e9-905d-f2b0544f3941.png)
点击删除页面还是存在，右上角一闪而过这个窗口，显示Success，但是内容是失败

**Comment by zaghost** [comment]
计划任务修改后保存，请求/sched/cron/返回错误500

```
File "/home/appuser/PycharmProjects/OpsManageV3/dao/crontab.py" in rsync_cron
  244.         result = ANS.handle_model_data(ANS.get_model_result(), 'cron',module_args)        

File "/home/appuser/PycharmProjects/OpsManageV3/utils/ansible/runner.py" in handle_model_data
  316.                         data['msg'] = y.get('stdout').replace('\t\t','<br>').replace('\r\n','<br>').replace('\t','<br>').replace('\n','<br>')

Exception Type: AttributeError at /sched/cron/
Exception Value: 'NoneType' object has no attribute 'replace'
```
数据没有stdout这个字段

**Comment by zaghost** [comment]
![图片](https://user-images.githubusercontent.com/8455736/61777180-19240e00-ae2f-11e9-8e5e-75531016c542.png)

\static\js\sched\cron.js
![图片](https://user-images.githubusercontent.com/8455736/61776824-5f2ca200-ae2e-11e9-9006-4f3dcfb045f2.png)

**Comment by zaghost** [comment]
数据库列表行点放大镜没反应
请求地址/api/db/org/1/，返回500

错误信息：
```
File "/home/appuser/PycharmProjects/OpsManageV3/api/views/db_api.py" in db_org
  165.         MYSQL = MySQLPool(host=dbServer.db_assets.server_assets.ip,port=dbServer.db_port,user=dbServer.db_user,passwd=dbServer.db_passwd,dbName=dbServer.db_name)

Exception Type: TypeError at /api/db/org/1/
Exception Value: __init__() got an unexpected keyword argument 'host'
```
dao.base.MySQLPool的__init__()中没有host这个参数，应该是dbServer

**Comment by welliamcao** [comment]
> 数据库列表行点放大镜没反应
> 请求地址/api/db/org/1/，返回500
> 
> 错误信息：
> 
> ```
> File "/home/appuser/PycharmProjects/OpsManageV3/api/views/db_api.py" in db_org
>   165.         MYSQL = MySQLPool(host=dbServer.db_assets.server_assets.ip,port=dbServer.db_port,user=dbServer.db_user,passwd=dbServer.db_passwd,dbName=dbServer.db_name)
> 
> Exception Type: TypeError at /api/db/org/1/
> Exception Value: __init__() got an unexpected keyword argument 'host'
> ```
> 
> dao.base.MySQLPool的__init__()中没有host这个参数，应该是dbServer

你这个是旧代码吧，这个功能都去掉了。

**Comment by zaghost** [comment]
> 
> 
> > 数据库列表行点放大镜没反应
> > 请求地址/api/db/org/1/，返回500
> > 错误信息：
> > ```
> > File "/home/appuser/PycharmProjects/OpsManageV3/api/views/db_api.py" in db_org
> >   165.         MYSQL = MySQLPool(host=dbServer.db_assets.server_assets.ip,port=dbServer.db_port,user=dbServer.db_user,passwd=dbServer.db_passwd,dbName=dbServer.db_name)
> > 
> > Exception Type: TypeError at /api/db/org/1/
> > Exception Value: __init__() got an unexpected keyword argument 'host'
> > ```
> > 
> > 
> > dao.base.MySQLPool的__init__()中没有host这个参数，应该是dbServer
> 
> 你这个是旧代码吧，这个功能都去掉了。

最新的代码呀
功能还在的
![图片](https://user-images.githubusercontent.com/8455736/61928478-282fcb00-afab-11e9-96ba-d9dc57a8c588.png)


https://github.com/welliamcao/OpsManage/blob/v3/api/views/db_api.py的165行
https://github.com/welliamcao/OpsManage/blob/v3/dao/base.py的141行
参数名不一样

**Comment by welliamcao** [comment]
> > > 数据库列表行点放大镜没反应
> > > 请求地址/api/db/org/1/，返回500
> > > 错误信息：
> > > ```
> > > File "/home/appuser/PycharmProjects/OpsManageV3/api/views/db_api.py" in db_org
> > >   165.         MYSQL = MySQLPool(host=dbServer.db_assets.server_assets.ip,port=dbServer.db_port,user=dbServer.db_user,passwd=dbServer.db_passwd,dbName=dbServer.db_name)
> > > 
> > > Exception Type: TypeError at /api/db/org/1/
> > > Exception Value: __init__() got an unexpected keyword argument 'host'
> > > ```
> > > 
> > > 
> > > dao.base.MySQLPool的__init__()中没有host这个参数，应该是dbServer
> > 
> > 
> > 你这个是旧代码吧，这个功能都去掉了。
> 
> 最新的代码呀
> 功能还在的
> ![图片](https://user-images.githubusercontent.com/8455736/61928478-282fcb00-afab-11e9-96ba-d9dc57a8c588.png)
> 
> [https://github.com/welliamcao/OpsManage/blob/v3/api/views/db_api.py的165行](https://github.com/welliamcao/OpsManage/blob/v3/api/views/db_api.py%E7%9A%84165%E8%A1%8C)
> [https://github.com/welliamcao/OpsManage/blob/v3/dao/base.py的141行](https://github.com/welliamcao/OpsManage/blob/v3/dao/base.py%E7%9A%84141%E8%A1%8C)
> 参数名不一样

已修复。

**Comment by zaghost** [comment]
【剧本/脚本保存报错】部署脚本/剧本保存后，如果手工删除服务器上upload目录下的文件，再次修改保存时会报错，保存不了

**Comment by zaghost** [comment]
【部署剧本列表/部署剧本新建输入区域刷新问题】
点列表行的运行，再点添加按钮，输入区域不能刷新

**Comment by bwcsswcx** [comment]
![1](https://user-images.githubusercontent.com/50362405/63739152-dbe3ed80-c8be-11e9-9b4e-7465e54cf461.jpg)
全新安装最新v3版本的程序，错误提示如图，希望作者看看

**Comment by welliamcao** [comment]
> ![1](https://user-images.githubusercontent.com/50362405/63739152-dbe3ed80-c8be-11e9-9b4e-7465e54cf461.jpg)
> 全新安装最新v3版本的程序，错误提示如图，希望作者看看

清除项目下面migrations目录

**Comment by okay456okay** [comment]
【脚本工具-部署脚本列表超过10个时，后面的脚本在列表里无法编辑和删除】
添加了第11个脚本后，部署工具-脚本工具-部署脚本列表点击第2页的那个脚本（即第11个脚本）进行编辑或删除，没有任何反应。

**Comment by rocky1001** [comment]
【安装执行到：/usr/local/python3/bin/python3 manage.py migrate 时报错】
错误log如下：
````shell
Operations to perform:
  Apply all migrations: admin, apply, asset, auth, cicd, contenttypes, databases, deploy, django_celery_beat, django_celery_results, filemanage, navbar, orders, sched, sessions, wiki
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying asset.0001_initial... OK
  Applying apply.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying cicd.0001_initial... OK
  Applying databases.0001_initial...Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
````

**Comment by rocky1001** [comment]
> 【安装执行到：/usr/local/python3/bin/python3 manage.py migrate 时报错】
> 错误log如下：
> 
> ```shell
> Operations to perform:
>   Apply all migrations: admin, apply, asset, auth, cicd, contenttypes, databases, deploy, django_celery_beat, django_celery_results, filemanage, navbar, orders, sched, sessions, wiki
> Running migrations:
>   Applying contenttypes.0001_initial... OK
>   Applying auth.0001_initial... OK
>   Applying admin.0001_initial... OK
>   Applying admin.0002_logentry_remove_auto_add... OK
>   Applying admin.0003_logentry_add_action_flag_choices... OK
>   Applying asset.0001_initial... OK
>   Applying apply.0001_initial... OK
>   Applying contenttypes.0002_remove_content_type_name... OK
>   Applying auth.0002_alter_permission_name_max_length... OK
>   Applying auth.0003_alter_user_email_max_length... OK
>   Applying auth.0004_alter_user_username_opts... OK
>   Applying auth.0005_alter_user_last_login_null... OK
>   Applying auth.0006_require_contenttypes_0002... OK
>   Applying auth.0007_alter_validators_add_error_messages... OK
>   Applying auth.0008_alter_user_username_max_length... OK
>   Applying auth.0009_alter_user_last_name_max_length... OK
>   Applying cicd.0001_initial... OK
>   Applying databases.0001_initial...Traceback (most recent call last):
>   File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
>     return self.cursor.execute(sql)
>   File "/usr/local/python3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
>     return self.cursor.execute(query, args)
>   File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
>     self.errorhandler(self, exc, value)
>   File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
>     raise errorvalue
>   File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
>     res = self._query(query)
>   File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
>     rowcount = self._do_query(q)
>   File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
>     db.query(q)
>   File "/usr/local/python3/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
>     _mysql.connection.query(self, query)
> _mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
> ```

上面的错误是因为创建opsmanage db时，使用的字符集不对，使用了：utf8mb4；
重新创建db并将字符集换成utf8后就正常了。供后来的同学参考。

**Comment by welliamcao** [comment]
> 【脚本工具-部署脚本列表超过10个时，后面的脚本在列表里无法编辑和删除】
> 添加了第11个脚本后，部署工具-脚本工具-部署脚本列表点击第2页的那个脚本（即第11个脚本）进行编辑或删除，没有任何反应。

谢谢反馈，已修复，[详见](https://github.com/welliamcao/OpsManage/commit/3f6c0b3811712766427f8b8466cb79bc841e909f)

**Comment by okay456okay** [comment]
> > 【脚本工具-部署脚本列表超过10个时，后面的脚本在列表里无法编辑和删除】
> > 添加了第11个脚本后，部署工具-脚本工具-部署脚本列表点击第2页的那个脚本（即第11个脚本）进行编辑或删除，没有任何反应。
> 
> 谢谢反馈，已修复，[详见](https://github.com/welliamcao/OpsManage/commit/3f6c0b3811712766427f8b8466cb79bc841e909f)

合并代码后发现新建的脚本和原来的脚本在列表里都显示不出来了

**Comment by welliamcao** [comment]
> > > 【脚本工具-部署脚本列表超过10个时，后面的脚本在列表里无法编辑和删除】
> > > 添加了第11个脚本后，部署工具-脚本工具-部署脚本列表点击第2页的那个脚本（即第11个脚本）进行编辑或删除，没有任何反应。
> > 
> > 
> > 谢谢反馈，已修复，[详见](https://github.com/welliamcao/OpsManage/commit/3f6c0b3811712766427f8b8466cb79bc841e909f)
> 
> 合并代码后发现新建的脚本和原来的脚本在列表里都显示不出来了

接口报错了吗？

**Comment by okay456okay** [comment]
> > > > 【脚本工具-部署脚本列表超过10个时，后面的脚本在列表里无法编辑和删除】
> > > > 添加了第11个脚本后，部署工具-脚本工具-部署脚本列表点击第2页的那个脚本（即第11个脚本）进行编辑或删除，没有任何反应。
> > > 
> > > 
> > > 谢谢反馈，已修复，[详见](https://github.com/welliamcao/OpsManage/commit/3f6c0b3811712766427f8b8466cb79bc841e909f)
> > 
> > 
> > 合并代码后发现新建的脚本和原来的脚本在列表里都显示不出来了
> 
> 接口报错了吗？

可能是重启ops_web程序有问题，导致旧程序没杀掉，今天杀掉后重启就好了，supervisor里加下配置：
stopasgroup=true             ; send stop signal to the UNIX process group (default false)
killasgroup=true             ; SIGKILL the UNIX process group (def false)

**Comment by okay456okay** [comment]
添加一个普通用户后，无法将一个服务器分配给这个普通用户，试过几个办法：
1. 添加一个组，组权限添加以资产管理开头的所有权限（或者添加所有权限），将普通用户添加到这个组里
2. 用这个普通用户添加这个服务器
3. 用服务器的使用组改为1中添加的组
4. 将服务器的购买人改为这个普通用户

使用上述几步的配置均无法将服务器分配给普通用户，即新加的这个普通用户在CMDB - 资产列表 无法看到任何服务器。

**Comment by welliamcao** [comment]
> 添加一个普通用户后，无法将一个服务器分配给这个普通用户，试过几个办法：
> 
> 1. 添加一个组，组权限添加以资产管理开头的所有权限（或者添加所有权限），将普通用户添加到这个组里
> 2. 用这个普通用户添加这个服务器
> 3. 用服务器的使用组改为1中添加的组
> 4. 将服务器的购买人改为这个普通用户
> 
> 使用上述几步的配置均无法将服务器分配给普通用户，即新加的这个普通用户在CMDB - 资产列表 无法看到任何服务器。

在用户中心，有个显示器图标按钮，点击分配。

**Comment by okay456okay** [comment]
<img width="1770" alt="图片" src="https://user-images.githubusercontent.com/1276541/65114286-d2aaf400-da18-11e9-8647-2b99fff055cf.png">
从左到右依次是编辑、查看信息、更新信息、更新硬盘信息、Terminal连接、删除，哪个是分配按钮，抱歉一直没有找到。

**Comment by welliamcao** [comment]
> <img alt="图片" width="1770" src="https://user-images.githubusercontent.com/1276541/65114286-d2aaf400-da18-11e9-8647-2b99fff055cf.png">
> 
> 从左到右依次是编辑、查看信息、更新信息、更新硬盘信息、Terminal连接、删除，哪个是分配按钮，抱歉一直没有找到。

用户中心，不是资产列表

**Comment by okay456okay** [comment]
> > <img alt="图片" width="1770" src="https://user-images.githubusercontent.com/1276541/65114286-d2aaf400-da18-11e9-8647-2b99fff055cf.png">
> > 从左到右依次是编辑、查看信息、更新信息、更新硬盘信息、Terminal连接、删除，哪个是分配按钮，抱歉一直没有找到。
> 
> 用户中心，不是资产列表

用户中心也没看到分配，您能截个图吗？ 多谢
<img width="2031" alt="图片" src="https://user-images.githubusercontent.com/1276541/65203905-23752800-dabf-11e9-9ff3-9d635a55060c.png">

**Comment by welliamcao** [comment]
> > > <img alt="图片" width="1770" src="https://user-images.githubusercontent.com/1276541/65114286-d2aaf400-da18-11e9-8647-2b99fff055cf.png">
> > > 从左到右依次是编辑、查看信息、更新信息、更新硬盘信息、Terminal连接、删除，哪个是分配按钮，抱歉一直没有找到。
> > 
> > 
> > 用户中心，不是资产列表
> 
> 用户中心也没看到分配，您能截个图吗？ 多谢
> <img alt="图片" width="2000" src="https://user-images.githubusercontent.com/1276541/65203905-23752800-dabf-11e9-9ff3-9d635a55060c.png">

我说错了，在用户管理，用户列表
![image](https://user-images.githubusercontent.com/5885314/65204683-97afcb80-dabf-11e9-988e-9927af49e0d9.png)

**Comment by bobzhanggmail** [comment]
【资产管理，用户中心】无法批量删除资产，选中几个资产后，点删除图标，弹出提示：请至少选择一个资产!
单点资产后面的删除图标可以删除。

**Comment by xiaogangfighting** [comment]
普通用户无法查看代码发布--项目列表，发现是接口报错：http://ip/api/apps/list/
![1111117174444](https://user-images.githubusercontent.com/5702303/70984155-f69fd380-20f4-11ea-8200-ad7b0ce8d9a9.png)

ps:普通用户已经添加了如下权限
![image](https://user-images.githubusercontent.com/5702303/70984277-2353eb00-20f5-11ea-9ec7-14ca344e1ffe.png)
![image](https://user-images.githubusercontent.com/5702303/70984326-3961ab80-20f5-11ea-8592-fd20c341d85d.png)

**Comment by welliamcao** [comment]
> 普通用户无法查看代码发布--项目列表，发现是接口报错：http://ip/api/apps/list/
> ![1111117174444](https://user-images.githubusercontent.com/5702303/70984155-f69fd380-20f4-11ea-8200-ad7b0ce8d9a9.png)
> 
> ps:普通用户已经添加了如下权限
> ![image](https://user-images.githubusercontent.com/5702303/70984277-2353eb00-20f5-11ea-9ec7-14ca344e1ffe.png)
> ![image](https://user-images.githubusercontent.com/5702303/70984326-3961ab80-20f5-11ea-8592-fd20c341d85d.png)

我检查一下。

**Comment by xiaogangfighting** [comment]
> > 普通用户无法查看代码发布--项目列表，发现是接口报错：http://ip/api/apps/list/
> > ![1111117174444](https://user-images.githubusercontent.com/5702303/70984155-f69fd380-20f4-11ea-8200-ad7b0ce8d9a9.png)
> > ps:普通用户已经添加了如下权限
> > ![image](https://user-images.githubusercontent.com/5702303/70984277-2353eb00-20f5-11ea-9ec7-14ca344e1ffe.png)
> > ![image](https://user-images.githubusercontent.com/5702303/70984326-3961ab80-20f5-11ea-8592-fd20c341d85d.png)
> 
> 我检查一下。

你那边可以复现这个问题么？

**Comment by frank0826** [comment]
普通用户报错无权限，用户所在的角色组中已添加项目发布管理权限
![image](https://user-images.githubusercontent.com/11606105/72235723-b3ab2000-360e-11ea-890e-668702fd594e.png)

项目列表中显示为空:
![image](https://user-images.githubusercontent.com/11606105/72235769-e8b77280-360e-11ea-840f-e5489ee72ed0.png)

**Comment by blueiq** [comment]
【表单验证bug】v3在新增资产、申请工单等，表单空值验证在输入第一个字段如资产编号后就可以直接提交，后续字段不在检查了。

**Comment by welliamcao** [comment]
> 普通用户报错无权限，用户所在的角色组中已添加项目发布管理权限
> ![image](https://user-images.githubusercontent.com/11606105/72235723-b3ab2000-360e-11ea-890e-668702fd594e.png)
> 
> 项目列表中显示为空:
> ![image](https://user-images.githubusercontent.com/11606105/72235769-e8b77280-360e-11ea-840f-e5489ee72ed0.png)

更新一下代码修复了，前段时间没有空处理。
@frank0826 @xiaogangfighting

**Comment by frank0826** [comment]
代码发布
成员管理已经添加为管理人员
![image](https://user-images.githubusercontent.com/11606105/72506601-2b7e8200-387d-11ea-8e7b-01d40a2ceb3b.png)

**Comment by dosealy** [comment]
opsmanage_use 表呢 sql脚本没有这个表结构

**Comment by welliamcao** [comment]
现在不要用docker部署方式，最近更新频繁，docker部署文档没有更新，建议用release里面的包部署



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dosealy <notifications@github.com&gt;
发送时间: 2020年5月19日 16:33
收件人: welliamcao/OpsManage <OpsManage@noreply.github.com&gt;
抄送: William.Cao <303350019@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[welliamcao/OpsManage] V3测试版本BUG反馈 (#154)





 
opsmanage_use 表呢 sql脚本没有这个表结构

**Comment by Zhang21** [comment]
[资产列表无法获取]  v3, mysql 5.7的`sql_mode`已经修改：
1. 添加资产成功后页面不跳转，但已成功；
2. 无法获取资产列表，后端报500错误(`/assets/search/`)。

解决办法: 我暂时回滚到`3.0.2`之后，没有这个问题。

**Comment by Zhang21** [comment]
[工单系统]    工单系统无法显示审核人，后台已经提示200。前端没有用户。由于审核人是必填项，这样导致无法创建工单。

**Comment by welliamcao** [comment]
> [工单系统] 工单系统无法显示审核人，后台已经提示200。前端没有用户。由于审核人是必填项，这样导致无法创建工单。

审核人是自己的上级，要先给用户分配上级

**Comment by welliamcao** [comment]
> [资产列表无法获取] v3, mysql 5.7的`sql_mode`已经修改：
> 
> 1. 添加资产成功后页面不跳转，但已成功；
> 2. 无法获取资产列表，后端报500错误(`/assets/search/`)。
> 
> 解决办法: 我暂时回滚到`3.0.2`之后，没有这个问题。

不知道你这个是不是因为5.7的问题，你看看这个https://github.com/welliamcao/OpsManage/issues/18#issuecomment-360701544
