### ISSUE TITLE
启动部署OpsManage平台失败

### ISSUE THREAD

**Issue by linhut** [welliamcao/OpsManage#164]
```
[root@localhost OpsManage]# python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
March 12, 2019 - 10:54:56
Django version 1.11.7, using settings 'OpsManage.settings'
Starting Channels development server at http://0.0.0.0:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 176, in run
    worker.run()
  File "/usr/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/lib/python2.7/site-packages/asgi_redis/core.py", line 168, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 176, in run
    worker.run()
  File "/usr/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/lib/python2.7/site-packages/asgi_redis/core.py", line 168, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 176, in run
    worker.run()
  File "/usr/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/lib/python2.7/site-packages/asgi_redis/core.py", line 168, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 176, in run
    worker.run()
  File "/usr/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/lib/python2.7/site-packages/asgi_redis/core.py", line 168, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```
提示线程错误，部署失败，请问可以解答下么？

**Comment by welliamcao** [comment]
`ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`
redis连接不上
