### ISSUE TITLE
关于部署

### ISSUE THREAD

**Issue by lovese** [welliamcao/OpsManage#18]
您好，对您这个项目很感兴趣，README里面部署过程中安装了easy_install，但是我看后面部署过程都没用过这个命令，这是为什么？

**Comment by welliamcao** [comment]
pip需要easy_install

**Comment by lovese** [comment]
我的centos7系统，自带python2.7.5，安装epel源的python2-pip代替您的pip可以用吗？

**Comment by welliamcao** [comment]
可以的pip版本无所谓，能安装平台所需模块就可以。

**Comment by lovese** [comment]
pip install django==1.8.17这个版本是固定的吗？ 
pip install ansible==2.2.2这个版本是必须等于我安装的版本么？

**Comment by welliamcao** [comment]
有指定版本的按照要求安装，没有就不用

**Comment by liuxiaoxiong** [comment]
TypeError at /login/
render_to_response() got an unexpected keyword argument 'context_instance'
大师好，为啥我部署的时候报错这个？这个是啥意思呢？

**Comment by welliamcao** [comment]
python模块都按要求安装成功了吗？

**Comment by liuxiaoxiong** [comment]
恩，模块都安装了，是访问的时候报错的，好像是这段代码有问题
view--->index.py 96行
return render_to_response('login.html',context_instance=RequestContext(request))

**Comment by welliamcao** [comment]
@liuxiaoxiong 提供一下django与python版本？

**Comment by liuxiaoxiong** [comment]
Python Version: | 2.7.5
Django Version: | 1.11.2

**Comment by welliamcao** [comment]
@liuxiaoxiong pip install django==1.8.17试一下这个版本，可能你的Django版本太高了，render_to_response不支持context_instance了

**Comment by liuxiaoxiong** [comment]
感谢，果然是这个问题！！

**Comment by lovese** [comment]
生成数据表时报错
/usr/lib64/python2.7/site-packages/django/db/backends/mysql/base.py:124: Warning: Incorrect string value: '\xE6\x80\xBB\xE8\xB5\x84...' for column 'name' at row 1
  return self.cursor.execute(query, args)
还望帮忙看下
不清楚是不是redis设置了密码的缘故

**Comment by welliamcao** [comment]
@lovese 能提供一下MySQL版本信息吗？

**Comment by lovese** [comment]
Server version: 5.5.52-MariaDB MariaDB Server
配置完OpsManage，在第八步生成数据表时出现的

**Comment by welliamcao** [comment]
@lovese MySQL字符集有没有配置过？（需要重启MySQL）
```
[mysqld]
default-character-set = utf8
character_set_server = utf8
```

**Comment by lovese** [comment]
/etc/my.cnf.d/client.cnf
[client]
default-character-set=utf8

/etc/my.cnf.d/server.cnf
[mysqld]
character-set-server=utf8

**Comment by lovese** [comment]
我把库删了重新建库就可以了，应该是要配置好数据库再建库，前面有重启过的，没起作用

**Comment by lovese** [comment]
您好，我的redis本来就装过了还设置了密码，我直接拿来用还要进行哪里配置吗？

**Comment by welliamcao** [comment]
@lovese redis暂时不支持认证。

**Comment by lovese** [comment]
我配置了使用组，但是不显示，硬盘总容量也读取不到，提示不支持，内存详细信息及硬盘详细信息也没有内容，带宽用的基本都是双线路了，云硬盘也没有raid，这个管理平台好像更适合物理机，对云服务器好像不太完全适配

**Comment by welliamcao** [comment]
基础资产需要自己配置，更新raid与内存，需要模块GitHub上面不提供，如果需要贴合公司环境，可以找我付费定制。

**Comment by lovese** [comment]
好的

**Comment by slimshadowg** [comment]
Unhandled exception in thread started by <function wrapper at 0x7fc670415de8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 237, in wrapper
    filename = traceback.extract_tb(tb)[-1][0]
TypeError: 'NoneType' object is not callable
按照大师流程做的，期间安装模块出错，更新pip后完成安装，启动runserver时卡住control^c退出显示这个信息

**Comment by welliamcao** [comment]
@slimshadowg 是不是pip install -r requirements.txt这个步骤出现错误或者警告被忽略了？

**Comment by slimshadowg** [comment]
安装channels模块不能安装,更新pip后才能安装,安装完成后启动就卡住

**Comment by shihuizhen** [comment]
channels 安装问题 Twisted版本不对
wget https://pypi.python.org/packages/a2/37/298f9547606c45d75aa9792369302cc63aa4bbcf7b5f607560180dd099d2/Twisted-17.9.0.tar.bz2#md5=6dbedb918f0c7288a4c670f59393ecf8
tar -xjvf Twisted-17.9.0.tar.bz2
cd Twisted-17.9.0
python setup.py install

**Comment by slimshadowg** [comment]
@shihuizhen 十分感谢，问题解决了

**Comment by shihuizhen** [comment]
当前代码使用pip install ansible==2.3.2.0，如果装2.2.2.0 的话会出现ansible 执行失败，原因是paramiko 问题。报错
`/opt/env/opsmanage/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 126, in run\n    res = self._execute()\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 511, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/action/normal.py\", line 33, in run\n    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 584, in _execute_module\n    tmp = self._make_tmp_path(remote_user)\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 224, in _make_tmp_path\n    tmpdir =  self._remote_expand_user(C.DEFAULT_REMOTE_TMP, sudoable=False)\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 505, in _remote_expand_user\n    data = self._low_level_execute_command(cmd, sudoable=False)\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 777, in _low_level_execute_command\n    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py\", line 253, in exec_command\n    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/connection/__init__.py\", line 52, in wrapped\n    self._connect()\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py\", line 141, in _connect\n    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py\", line 212, in _connect_uncached\n    sock_kwarg = self._parse_proxy_command(port)\n  File \"/opt/env/opsmanage/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py\", line 153, in _parse_proxy_command\n    args = self._split_ssh_args(' '.join(ssh_args))\nTypeError: sequence item 0: expected string, NoneType found\n`

我的pip freeze
`amqp==1.4.9
ansible==2.3.2.0
anyjson==0.3.3
asgi-redis==1.4.3
asgiref==1.1.2
asn1crypto==0.24.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
bcrypt==3.1.4
billiard==3.3.0.23
celery==3.1.20
celery-with-redis==3.0
cffi==1.11.2
channels==1.1.7
constantly==15.1.0
cryptography==2.1.4
daphne==1.4.2
DBUtils==1.2
Django==1.11.7
django-celery==3.2.2
djangorestframework==3.5.3
enum34==1.1.6
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.19
Jinja2==2.10
kombu==3.0.37
MarkupSafe==1.0
meld3==1.0.2
msgpack==0.5.0
msgpack-python==0.5.0
MySQL-python==1.2.5
paramiko==2.4.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
pycrypto==2.6.1
PyNaCl==1.2.1
pyOpenSSL==17.5.0
pytz==2017.3
PyYAML==3.12
redis==2.10.6
service-identity==17.0.0
six==1.11.0
supervisor==3.3.3
Twisted==17.9.0
txaio==2.8.2
xlrd==1.1.0
zope.interface==4.4.3`

**Comment by welliamcao** [comment]
@shihuizhen 应该跟你用CentOS 7.4有关，如果是CentOS 6使用requirements.txt安装模块是低版本的paramiko，高版本的paramiko应该跟ansible 2.2代码不兼容

**Comment by shihuizhen** [comment]
可能跟我用的pip 源有关系。我用的是阿里的pip 源。

**Comment by dongwenrong** [comment]
安装python相关包，有谁遇到如下错误吗？请指教！谢谢！
Exception:
Traceback (most recent call last):
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/opt/OpsManage/ENV/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'asgiref ~=1.1', 'at', ' ~=1.1')

Storing debug log for failure in /root/.pip/pip.log

**Comment by welliamcao** [comment]
@dongwenrong  先升级一下pip`pip install -U pip`，然后再` pip install -r requirements.txt`试一下

**Comment by dongwenrong** [comment]
@welliamcao 非常感谢快速准确的回复，问题已解决。谢谢~

**Comment by dongwenrong** [comment]
记录一下：
执行python manage.py makemigrations OpsManage  遇到错误：
需要安装:pip install mysql-replication

**Comment by welliamcao** [comment]
@dongwenrong 非常感谢，因为引入了Binlog2sql，但是requirements.txt文件还未更新，晚点更新requirements.txt文件，加入mysql-replication，pymysql这个两个模块。

**Comment by byakkozhang** [comment]
如安装的是mysql5.7+，需要关闭mysql的“ ONLY_FULL_GROUP_BY”

#先查询
select @@global.sql_mode
 
#再修改
set @@global.sql_mode=‘STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;

**Comment by wangr927** [comment]
你好，我这用docker安装了redis和mysql,然后启动，已经pip install -r requirements.txt 
python manage.py makemirgrations ... 向mysql写入数据时提示错误
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/lib64/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/lib64/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib64/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'OpsManage.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djcelery
```
我看OpsManage 这个app的目录内，既没有djcelery.py的文件，也没有这样的目录，并且pip 也无法安装。我看了下，这个应该是个插件之类的，djcelery在app有注册过，在setting中，也有加载的动作。
我应该到哪里寻找这些代码

**Comment by welliamcao** [comment]
@wangr927 django-celery是不是没安装成功？

**Comment by iamscorpiomm** [comment]
感谢楼主分享~
我已经进行到 九、启动部署平台 这一步了，已经可以通过web访问了。
研究了大概4小时，我的django基础有点忘了，所以安装过程遇到了比较多的问题，列举一下，供参考。

pip install -r requirements.txt
这一步也是出错的，缺少gcc，还需要安装 twisted。

redis安装，报错：Error jemalloc/jemalloc.h: No such file or directory
按照 http://blog.csdn.net/lgh1117/article/details/48270085 的方法解决了。

mysql配置，default-character-set = utf8，character_set_server = utf8
character_set_server，是拼写错误的，我这样配置，mysql出错，根本启动不起来，改成 character-set-server 就可以了。
default-character-set，我进入mysql命令行，执行 show variables like "%default%"; 根本没有这个变量，在/etc/my.cnf里一添加这个变量就无法启动mysql失败。
总之，我只添加了 character-set-server = utf8 就成功的往下进行了。

OpsManage启动
需要关闭防火墙，需要启动nginx（安装nginx又需要先安装epel-release），这些是django项目的基本要求，不能web只能本机curl访问，其他机器无法访问。
我很久没碰django了，这些基础知识忘了，费了会功夫才记得配上这些的。
建议把这些基础要求注明在部署手册里，新手需要。

**Comment by iamscorpiomm** [comment]
再补充一个。

七、配置OpsManage
TEMPLATE_DIRS 和 TEMPLATES 的配置好像是冲突的。
我下载下来的代码里， TEMPLATE_DIRS是被注释掉的，我取消注释，项目启动失败，于是我就保留注释了，就正常了。

**Comment by iamscorpiomm** [comment]
再补充一个。
我点击 Dashboard 菜单的时候报错：ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'opsmanage.opsmanage_project_order.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
traceback一下，是index函数的 SELECT id,order_user FROM opsmanage_project_order GROUP BY order_user; 这条语句查询失败了。
乍一看这语句没啥毛病，其实跟mysql的设置有关，跟Opsmanage没关系。

我的mysql安装后，默认的sql_mode包含了only_full_group_by这个值，指的是对sql语句的group by语法的一种检查。把这个值去年，

**Comment by zhoushao12** [comment]
Request Method: | GET
-- | --
http://192.168.165.131:8000/assets_list
1.11.7
OperationalError
(1054, "Unknown column 'opsmanage_networkcard_assets.ip' in 'field list'")
/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py in execute_sql, line 894
/usr/bin/python
2.7.5
['/mnt/OpsManage',  '/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib/python2.7/site-packages',  '/usr/lib/python2.7/site-packages/setuptools-28.0.0-py2.7.egg']
Wed, 28 Mar 2018 15:58:31 +0800

这个是什么问题：

**Comment by welliamcao** [comment]
你是用新版的代码，运行在旧的数据库上面吗？@zhoushao12

**Comment by Macroldj** [comment]
用新代码，感觉有些数据库不存在。

**Comment by Macroldj** [comment]
![image](https://user-images.githubusercontent.com/29014318/56946194-0d8cb800-6b5c-11e9-99c0-5f3c895a0a08.png)

**Comment by lijianqiao** [comment]
大家好，请问我在python manage.py runserver 0.0.0.0:8000时候，下面显示有错误，如下
[INFO] server.py[line:106] HTTP/2 support not enabled (install the http2 and tls Twisted extras)，
我安装了TWisted ，但是http2没有，请问是需要安装么？还是我哪里配置的有问题

**Comment by Coffe2Cat** [comment]
请问老师 第九步 启动平台部署的 前四行内容具体是什么意思，没太看明白，尤其是第一行和第四行
# echo_supervisord_conf > /etc/supervisord.conf
# export PYTHONOPTIMIZE=1
# vim /etc/supervisord.conf
最后添加，/var/log/celery-*.log这些是日志文件，如果有错误请注意查看，directory的值是代码路径

**Comment by welliamcao** [comment]
> 请问老师 第九步 启动平台部署的 前四行内容具体是什么意思，没太看明白，尤其是第一行和第四行
> 
> # echo_supervisord_conf > /etc/supervisord.conf
> # export PYTHONOPTIMIZE=1
> # vim /etc/supervisord.conf
> 最后添加，/var/log/celery-*.log这些是日志文件，如果有错误请注意查看，directory的值是代码路径

1、生成supervisor配置文件
2、让celery支持ansible api
3、通过日志文件平排查celery是否正常

**Comment by Coffe2Cat** [comment]
![image](https://user-images.githubusercontent.com/17587602/79240795-ce5a9280-7ea4-11ea-945a-0ffc0365950c.png)
部署完之后，点创建账号报错，请问这个是什么问题？

**Comment by welliamcao** [comment]
用管理员登陆，到用户中心创建账户



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Coffe2Cat <notifications@github.com&gt;
发送时间: 2020年4月14日 23:09
收件人: welliamcao/OpsManage <OpsManage@noreply.github.com&gt;
抄送: William.Cao <303350019@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[welliamcao/OpsManage] 关于部署 (#18)







部署完之后，点创建账号报错，请问这个是什么问题？

**Comment by liuliangliangyyp** [comment]
aceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'ldap'


大佬，报这个错

**Comment by liuliangliangyyp** [comment]
已解决是opsmanger.ini配置文件的配置问题

**Comment by Macroldj** [comment]
ok

liuliangliangyyp <notifications@github.com> 于2020年4月15日周三 上午10:48写道：

**Comment by cqvienet** [comment]
在执行/usr/local/python3/bin/python3 manage.py migrate时报不能创建外键，我看SQL初始化的时候关闭了外键检测的！_mysql_exceptions.IntegrityError: (1215, 'Cannot add foreign key constraint')

**Comment by welliamcao** [comment]
> 在执行/usr/local/python3/bin/python3 manage.py migrate时报不能创建外键，我看SQL初始化的时候关闭了外键检测的！_mysql_exceptions.IntegrityError: (1215, 'Cannot add foreign key constraint')

按照文档部署，生成表结构
```# /usr/local/python3/bin/python3 manage.py makemigrations account
# /usr/local/python3/bin/python3 manage.py makemigrations wiki
# /usr/local/python3/bin/python3 manage.py makemigrations orders
# /usr/local/python3/bin/python3 manage.py makemigrations navbar
# /usr/local/python3/bin/python3 manage.py makemigrations databases
# /usr/local/python3/bin/python3 manage.py makemigrations asset
# /usr/local/python3/bin/python3 manage.py makemigrations deploy
# /usr/local/python3/bin/python3 manage.py makemigrations cicd
# /usr/local/python3/bin/python3 manage.py makemigrations sched
# /usr/local/python3/bin/python3 manage.py makemigrations apply
# /usr/local/python3/bin/python3 manage.py migrate
# /usr/local/python3/bin/python3 manage.py createsuperuser  #创建管理员账户与密码
```

**Comment by zjyang86** [comment]
![image](https://user-images.githubusercontent.com/40283462/224213446-578f6034-f98e-4d56-a672-1efe5d5a9525.png)
请问这是什么问题？  刚部署上去就报这错，整个页面会卡死
