### ISSUE TITLE
项目部署报错

### ISSUE THREAD

**Issue by yxiaoy6** [welliamcao/OpsManage#194]
2019-07-19 14:14:12 [WARNING] Set redis key failed: Invalid input of type: 'SimpleLazyObject'. Convert to a byte, string or number first.
2019-07-19 14:14:13 [ERROR] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/daphne/http_protocol.py", line 274, in serverResponse
    "size": self.sentLength,
  File "/usr/lib/python2.7/site-packages/daphne/http_protocol.py", line 421, in log_action
    self.action_logger(protocol, action, details)
  File "/usr/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 145, in log_action
    sys.stderr.write(msg)
IOError: [Errno 5] Input/output error

2019-07-19 14:14:52 [ERROR] webssh获取用户[AnonymousUser]信息失败: User matching query does not exist.

**Comment by welliamcao** [comment]
没登录吗？怎么是匿名用户

**Comment by yxiaoy6** [comment]
登录了，选了两台目标机器。一台可以部署，另一台就部署失败，然后日志报的这个错

**Comment by welliamcao** [comment]
> 登录了，选了两台目标机器。一台可以部署，另一台就部署失败，然后日志报的这个错

看看redis模块，跟文档里面是否是一致的

**Comment by welliamcao** [comment]
问题解决了吗？
