### ISSUE TITLE
项目部署报错

### ISSUE THREAD

**Issue by jym503558564** [welliamcao/OpsManage#198]
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jym/OpsManage/OpsManage/urls.py", line 18, in <module>
    from OpsManage.views import index,users
  File "/Users/jym/OpsManage/OpsManage/views/users.py", line 14, in <module>
    from utils.base import method_decorator_adaptor
  File "/Users/jym/OpsManage/utils/base.py", line 4, in <module>
    import magic
  File "/Users/jym/.virtualenvs/ops/lib/python3.6/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/62004089-29036100-b153-11e9-8fda-22df4b11196f.png)

**Comment by jym503558564** [comment]
一些库的版本问题，导致报错，后来替换了，就可以了
