### ISSUE TITLE
Docker支持OpsManage

### ISSUE THREAD

**Issue by welliamcao** [welliamcao/OpsManage#20]
https://github.com/welliamcao/OpsManage/wiki/Docker%E6%9E%84%E5%BB%BAOpsManage

**Comment by lklkxcxc** [comment]
更正一下Dockerfile：
FROM centos:latest
RUN yum install -y wget git zlib zlib-devel readline-devel sqlite-devel bzip2-devel openssl-devel gdbm-devel libdbi-devel ncurses-libs kernel-devel libxslt-devel libffi-devel python-devel mysql-devel zlib-devel sshpass libtool make
RUN cd /usr/local/src && wget https://github.com/pypa/pip/archive/1.5.5.tar.gz -O pip-1.5.5.tar.gz && wget https://pypi.python.org/packages/f7/94/eee867605a99ac113c4108534ad7c292ed48bf1d06dfe7b63daa51e49987/setuptools-28.0.0.tar.gz
RUN cd /usr/local/src && tar -xzvf setuptools-28.0.0.tar.gz && tar -xzvf pip-1.5.5.tar.gz && cd setuptools-28.0.0 && python setup.py install && cd ../pip-1.5.5 && python setup.py install
#COPY requirements.txt /usr/local/src
#RUN cd /usr/local/src && pip install -r requirements.txt
RUN mkdir -p /etc/ansible/ && echo -ne “[defaults]\nlibrary = /usr/share/ansible/my_modules/\nhost_key_checking = False\n” > /etc/ansible/ansible.cfg
#COPY ansible.cfg /etc/ansible/ansible.cfg
RUN pip install django==1.8.17 Celery==3.1.23 django-celery==3.1.17 celery-with-redis djangorestframework paramiko ansible==2.3.1 supervisor redis MySQL-python DBUtils anyjson amqp
EXPOSE 8000

**Comment by xiabai84** [comment]
试用了一下 docker 版本的，出现下面错误。。。

sudo docker run -it --name=opsmanage -v /home/bai/data/opsmanage/OpsManage:/mnt/OpsManage -p 8000:8000 django-rest:base python /mnt/OpsManage/manage.py runserver 0.0.0.0:8000
Unhandled exception in thread started by <function wrapper at 0x1f1e848>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named channels

**Comment by welliamcao** [comment]
@xiabai84 这个是1.0版本的Docker化方法，不适用2.0版本了
