### ISSUE TITLE
部署过程，在执行生成数据表的时候报错问题

### ISSUE THREAD

**Issue by jishunetwork** [welliamcao/OpsManage#245]
![image](https://user-images.githubusercontent.com/60526282/73577095-03b32f00-44b7-11ea-914a-80a366624e09.png)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/core/management/base.py", line 366, in execute
    self.check()
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/core/checks/urls.py", line 100, in check_url_settings
    value = getattr(settings, name)
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/python3/lib/python3.6/site-packages/Django-3.0.2-py3.6.egg/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen import

**Comment by jishunetwork** [comment]
Django版本不对

按照requirements.txt里面的版本安装
