### ISSUE TITLE
ImportError: cannot import name COMMAND

### ISSUE THREAD

**Issue by solonext-shi** [welliamcao/OpsManage#57]
[root@localhost OpsManage]# python manage.py runserver 192.168.26:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fc72425a938>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 55, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 1205, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 1282, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 934, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 207, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 306, in _check_backend_specific_checks
    return connection.validation.check_field(self, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 18, in check_field
    field_type = field.db_type(connection)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 614, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/usr/local/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 196, in data_types
    if self.features.supports_microsecond_precision:
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 371, in mysql_version
    with self.temporary_connection():
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 462, in temporary_connection
    cursor = self.cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 80, in Connect
    from MySQLdb.connections import Connection
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 20, in <module>
    from .constants import CLIENT, COMMAND, CR, FIELD_TYPE, SERVER_STATUS
ImportError: cannot import name COMMAND
这是什么错误

**Comment by welliamcao** [comment]
MySQL-python没安装成功吗？

**Comment by solonext-shi** [comment]
装过了，mysql装的是5.7的影响吗？

**Comment by welliamcao** [comment]
没有，进入python交换环境import MySQLdb 导入这个模块有错误吗？
`import MySQLdb`
`print MySQLdb.__version__`

**Comment by solonext-shi** [comment]
>>> import MySQLdb
>>> print MySQLdb.__version__
1.2.5
>>> 
没有错误，该装的都给装上了、目前还没找到是哪儿的问题

**Comment by solonext-shi** [comment]
@welliamcao ，  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 80, in Connect
    from MySQLdb.connections import Connection
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 20, in <module>
    from .constants import CLIENT, COMMAND, CR, FIELD_TYPE, SERVER_STATUS
ImportError: cannot import name COMMAND
会是哪儿些原因造成这个错误？

**Comment by activaigor** [comment]
If somebody will stuck into the same problem it may be connected if you use different MySQL drivers on your project.
For example, when using mysqlclient and pymysql with 
```pymysql.install_as_MySQLdb()```
defined somewhere in your project may cause this error. just be sure you are using only mysqlclient and error will gone

**Comment by Drachenfels** [comment]
re: @activaigor 

This is spot on, colleague of mine sneaked this line into the code and I was like WTH. ;-)

**Comment by xxu462** [comment]
> If somebody will stuck into the same problem it may be connected if you use different MySQL drivers on your project.
> For example, when using mysqlclient and pymysql with
> `pymysql.install_as_MySQLdb()`
> defined somewhere in your project may cause this error. just be sure you are using only mysqlclient and error will gone

Thanks brother, this solves my problems immediately.
