### ISSUE TITLE
执行pip install -r requirements.txt 这个时报错，这是什么原因

### ISSUE THREAD

**Issue by lyc20140320** [welliamcao/OpsManage#59]
Downloading from URL https://pypi.python.org/packages/63/c0/4a2d24cbc0d163ae02bb21eaa1d95311e3948a4fd532e2d6416a02e16471/asgi_redis-1.4.3-py2.py3-none-any.whl#md5=0a207e2a6a4256a7b3873b7e02ca15c4 (from https://pypi.python.org/simple/asgi-redis/)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/local/lib/python2.7/site-packages/pip-1.5.5-py2.7.egg/pip/_vendor/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'asgiref ~=1.1.2', 'at', ' ~=1.1.2')

**Comment by welliamcao** [comment]
换成easy_install asgiref安装试一试

**Comment by lyc20140320** [comment]
不行，还是这个错误

**Comment by lyc20140320** [comment]
我现在执行python manage.py makemigrations OpsManage时报错
ImportError: No module named twisted.internet
我安装twisted时又报错pip install twisted，CompressionError: bz2 module is not available
我已经安装了bzip2-devel了。这是怎么回事

**Comment by lyc20140320** [comment]
搞定了，启动后无法访问
[root@node3 OpsManage]# python manage.py runserver ip:8000
Performing system checks...

System check identified no issues (0 silenced).
December 22, 2017 - 11:29:55
Django version 1.11.7, using settings 'OpsManage.settings'
Starting Channels development server at http://ip:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C.
Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-12-22 11:29:55,894 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2017-12-22 11:29:55,894 - INFO - server - Using busy-loop synchronous mode on channel layer
2017-12-22 11:29:55,894 - INFO - server - Listening on endpoint tcp:port=8000:interface=ip

http://ip:8000/
无法访问此网站
192.168.1.211 拒绝了我们的连接请求。

**Comment by welliamcao** [comment]
IP要换成你自己服务器的ip

**Comment by lyc20140320** [comment]
换了，我就是用自己的服务器ip访问的

**Comment by welliamcao** [comment]
`[root@node3 OpsManage]# python manage.py runserver ip:8000`
换成：
`[root@node3 OpsManage]# python manage.py runserver 你的服务器IP地址:8000`

**Comment by lyc20140320** [comment]
解决了，感谢
