### ISSUE TITLE
数据库管理-Inception服务器 配置时报错

### ISSUE THREAD

**Issue by wl21787** [welliamcao/OpsManage#71]
Internal Server Error: /db/config/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view OpsManage.views.database.db_config didn't return an HttpResponse object. It returned None instead.
[2018/01/31 22:36:57] HTTP POST /db/config/ 500 [0.17, 192.168.0.1:47955]

**Comment by welliamcao** [comment]
请问是配置哪一项？

**Comment by wl21787** [comment]
1、数据库管理>>基础配置>>Inception服务器提交时
2、全局配置>>配置邮件提交时

**Comment by welliamcao** [comment]
@wl21787 您使用的代码是什么时候的，[2018/01/31 22:36:57] HTTP POST /db/config/  我查看了代码，这个url并没有post方法。：)

**Comment by wl21787** [comment]
@welliamcao 非常感谢您的回复，我再检查一下自己的环境。
