### ISSUE TITLE
需要安装gcc

### ISSUE THREAD

**Issue by staugur** [welliamcao/OpsManage#9]
首先建议要安装的模块写到requirements.txt文件中。
```
django==1.8.17
Celery
django-celery
celery-with-redis
djangorestframework
paramiko
ansible==2.2.2
redis
supervisor
redis
MySQL-python
DBUtils
```
其次，第一步yum安装各种包时，应该是需要gcc的，我用docker新环境，没有gcc，pip报错，大概就是：https://stackoverflow.com/questions/8102292/problems-installing-pycrypto-on-osx

**Comment by staugur** [comment]
另外，redis加了密码的情况，mysql改了端口的情况

**Comment by staugur** [comment]
默认pip install  Celery django-celery
貌似版本不兼容，我是默认py2.7
运行数据同步：
```
[root@bj-aliyun OpsManage]# python manage.py  migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/djcelery/models.py", line 16, in <module>
    from . import managers
  File "/usr/lib/python2.7/site-packages/djcelery/managers.py", line 18, in <module>
    from celery.utils.timeutils import maybe_timedelta
ImportError: No module named timeutils
```
此时两个模块版本
```
celery (4.0.2)
django-celery (3.2.1)
```
后来卸载celery重新安装 celery==3.1.20， 正常。

**Comment by iamscorpiomm** [comment]
也需要安装 twisted 模块
